apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-fiber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-fiber
  template:
    metadata:
      labels:
        app: go-fiber
    spec:
      containers:
      - name: go-mon
        image: davarski/go-fiber:latest
        imagePullPolicy: Always
        ports:
        - name: web
          containerPort: 9000
