apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-flask
  template:
    metadata:
      labels:
        app: python-flask
    spec:
      containers:
      - name: python-flask
        image: davarski/python-flask:latest
        imagePullPolicy: Always
        ports:
        - name: web
          containerPort: 8000
